import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

import Header from "../components/header";

// Configurar fonte local baixada
const cormorantGaramond = localFont({
  src: [
      {
          path: "../../public/fonts/CormorantGaramond-Regular.ttf",
          weight: "400",
          style: "normal",
      },
      {
          path: "../../public/fonts/CormorantGaramond-Regular.ttf",
          weight: "700",
          style: "normal",
      },
  ],
  variable: "--font-cormorant",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
